on:
  workflow_dispatch: 
  release:
    types: [created]


jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: entrypoint
      run: env

    - name: run py
      run: python3 main.py
